version: "3"
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER} 
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes: 
      - ./_data:/var/lib/mysql
    ports: 
      - "3306:3306"
  web:
    image: kkomelin/kudoo
    depends_on: 
      - db
    ports: 
      - "3000:3000"
